language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: vb6UNFEIw6dVbL7qtAktfcq4RI+LGhZYoLTFpxlJ0wgNIBoZKpGqMuzGRiv/ZEYgEPUZOfn/w9DEg+SwIvAmZMLE/pJBZGgIAa3F+ZPzLnh5Q0t1rY8iPIlIFGnEgvP9FDoSFHxe+AeV6csMr2JfA0ehot7PCuEISHz+VrYFv0EMyjzfQy7Lgyw+KLSn6+lmSW21Q6iQ7IPF9E2+6km+T/xDiLd1p+14ICHOINwdDpjk9Ij6WaZmUnWTLHocwnJQQ6uf8GJ4dfhOCN2aW2coV932JChXLUlmzOnv8oMOX9pTYrwVHV4SIp200fhfOMd+2ezuK7L8ROKpdc+fZIciWkMraaVNGNuRyig3iEQ+A+6p9n32sbx/Wq3phRXYgS/UAGP8R4jM83+6p8jmPkF2dwghtRHEcl3p8w9ry64P+XlwpXDgvo3N+RxmjTPfKw1vYjoiPiZ2w14WX0gEI4xnPSj9UypfL7R9U89i9L3SQwoGmX9CqjdqyzywGa/XVIdgDq8SksCl4dpyUg+TtdG8y8O1BKUrJmxSHeIGg30WMZpxtJdfRJ+VFbRxi/84Q2hzvBlU8AvXA0/f9Ri7JMM1igRAtvJM8WrfoOXTFesMf6NZ5yfJfP18KKFiJ/rxMZ0/lPMoSxFTIoZfEsq6ejQaMKoKHMpnwiJvJ9dAtYlKPe0=
  app: secure-stream-63035
  on:
    repo: kfujikawa/node-shopping-list-integration-tests
